---
title: "872Final.verson1"
author:
output: html_document
date: "2024-04-15"
---
\newpage
\tableofcontents 
\newpage
\listoftables 
\newpage
\listoffigures 
\newpage

```{r setup, include=FALSE}
# Set your working directory
library(tidyverse)
library(dplyr)
library(lubridate)
library(agricolae)
library(moments)
library(ggplot2)
library(GGally)
library(ggridges)
library(viridis)
library(RColorBrewer)
library(colormap)
library(ggthemes)
library(formatR)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)
library(here)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 4)
sf::sf_use_s2(FALSE)

#Checking directory
here()

# Set your ggplot theme
Hope.theme <- theme_base()  + 
  theme(
    line = element_line(color = 'darkgreen', linewidth = 2),
    rect = element_rect(color = 'darkgreen'),
    text = element_text(size = 12, color = 'darkgreen', face = "italic"),
    
    plot.title = element_text(size = 14, color = 'darkgreen', face = "bold", margin=margin(b=8)),
    axis.text = element_text(size = 12, color = 'darkgreen', face = "italic"),
    
    axis.ticks = element_line(color = 'darkgreen'),
    panel.grid.major =  element_line(color='cornsilk3', size=0.5),
    panel.grid.minor =  element_blank(),
    
    plot.background = element_rect(fill = 'azure2'),
    panel.background =  element_rect(fill = 'azure2'),
    legend.background = element_rect(fill = 'azure2'),
    legend.key = element_rect(fill = 'azure2'),
    legend.title = element_text(size = 12, face = "bold"),
    legend.position = 'none',
    
    complete = TRUE)

# Set my theme as default theme
theme_set(Hope.theme)

# Load your datasets
fall.brief <- read.csv(here("Data/Raw/Atlantic brief squid-fall-survey-points-data.csv"), skip = 3, stringsAsFactors = TRUE)
summer.brief <- read.csv(here("Data/Raw/Atlantic brief squid-summer-survey-points-data.csv"), skip = 3,  stringsAsFactors = TRUE)
spring.brief <- read.csv(here("Data/Raw/Atlantic brief squid-spring-survey-points-data.csv"), skip = 3,  stringsAsFactors = TRUE)

#Data Processing
fall.brief <- mutate(fall.brief, Season = "Fall")
summer.brief <- mutate(summer.brief, Season = "Summer")
spring.brief <- mutate(spring.brief, Season = "Spring")
squids <- bind_rows(fall.brief, summer.brief, spring.brief)

class(squids$wtcpue)
squids <- filter(squids, wtcpue > 0)

#Write out processed data
write.csv(squids, row.names = FALSE, file = here("Data/Processed/squids.csv"))
```


# Rationale and Research Questions



\newpage

# Dataset Information



\newpage

# Exploratory Analysis 

```{r, message=FALSE}
ggpairs(squids, columns =c(3, 5, 6, 7, 8),  
  axisLabels = "show")
```

#Table 
#Three Variables
```{r}
depth.summary <- squids %>%
  summarise(Mean=mean(Depth), Median=median(Depth), Max=max(Depth), Min=min(Depth), Skewness=skewness(Depth))
wtcpue.summary <- squids %>%
  summarise(Mean=mean(wtcpue), Median=median(wtcpue), Max=max(wtcpue), Min=min(wtcpue), Skewness=skewness(wtcpue))
latitude.summary <- squids %>%
  summarise(Mean=mean(LAT), Median=median(LAT), Max=max(LAT), Min=min(LAT), Skewness=skewness(LAT))

variables.summary <- bind_rows(depth.summary, wtcpue.summary, latitude.summary)
rownames(variables.summary) <- c("Depth", "WTCPUE", "Latitude")

knitr::kable(variables.summary, caption = "Statistical Summary of Variables, Depth, WTCPUE, Latitude")
```
#WTCPUE by year
```{r}
wtcpue.yearly.summary <- squids %>%
  group_by(Year) %>% 
  summarise(Observations=length(wtcpue), Mean=mean(wtcpue), Median=median(wtcpue), Max=max(wtcpue), Min=min(wtcpue), Skewness=skewness(wtcpue))

knitr::kable(wtcpue.yearly.summary, caption = "Statistical Summary of WTCPUE by Year")
```
#WTCPUE by season
```{r}
wtcpue.seasonal.summary <- squids %>%
  group_by(Season) %>% 
  summarise(Observations=length(wtcpue), Mean=mean(wtcpue), Median=median(wtcpue), Max=max(wtcpue), Min=min(wtcpue), Skewness=skewness(wtcpue))

knitr::kable(wtcpue.seasonal.summary, caption = "Statistical Summary of WTCPUE by Season")
```



#Map*1989+2019
```{r}
squids.1989.sf <- squids %>% 
 st_as_sf(coords = c('LON','LAT'),
           crs=4326) %>% 
  filter(Year==1989)

map1 <- mapview(squids.1989.sf,
        zcol='Depth',
        cex='wtcpue')

squids.2019.sf <- squids %>% 
 st_as_sf(coords = c('LON','LAT'),
           crs=4326) %>% 
  filter(Year==2019)

map2 <- mapview(squids.2019.sf,
        zcol='Depth',
        cex='wtcpue')

combined_map <- map1 + map2
combined_map
```

\newpage

# Analysis



## Question 1: <insert specific question here and add additional subsections for additional questions below, if needed>

## Question 2: 




\newpage

# Summary and Conclusions


\newpage

# References
<add references here if relevant, otherwise delete this section> 
