---
title: "Regression"
author: "Cynthia Zhou"
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
# Set your working directory
library(tidyverse)
library(dplyr)
library(lubridate)
library(agricolae)
library(moments)
library(ggplot2)
library(ggridges)
library(viridis)
library(RColorBrewer)
library(colormap)
library(ggthemes)
library(formatR)
library(sf)
library(leaflet)
library(mapview); mapviewOptions(fgb = FALSE)
library(here)
library(tseries)
library(forecast)
library(cowplot)
library(patchwork)
knitr::opts_chunk$set(tidy.opts=list(width.cutoff=80), tidy=TRUE)
knitr::opts_chunk$set(echo = TRUE)
options(scipen = 4)
sf::sf_use_s2(FALSE)

#Checking directory
here()

# Set your ggplot theme
Hope.theme <- theme_base()  + 
  theme(
    line = element_line(color = 'darkgreen', linewidth = 2),
    rect = element_rect(color = 'darkgreen'),
    text = element_text(size = 12, color = 'darkgreen', face = "italic"),
    
    plot.title = element_text(size = 14, color = 'darkgreen', face = "bold", margin=margin(b=8)),
    axis.text = element_text(size = 12, color = 'darkgreen', face = "italic"),
    
    axis.ticks = element_line(color = 'darkgreen'),
    panel.grid.major =  element_line(color='cornsilk3', size=0.5),
    panel.grid.minor =  element_blank(),
    
    plot.background = element_rect(fill = 'azure2'),
    panel.background =  element_rect(fill = 'azure2'),
    legend.background = element_rect(fill = 'azure2'),
    legend.key = element_rect(fill = 'azure2'),
    legend.title = element_text(size = 12, face = "bold"),
    legend.position = 'none',
    complete = TRUE)
```

```{r data import, message=FALSE, warning=FALSE}
at_data <- read_csv("Data/Processed/brief-squid.csv") %>% 
  filter(wtcpue!= 0) 
```

## Analysis

## 1. Change in Depth
```{r split}
at_sea <- at_data %>%
  group_by(Season,Year) %>%
  mutate(mean_dep = mean(Depth, na.rm = TRUE)
  ) %>%
  ungroup()

# Spring
at_spr <- at_data %>%
  filter(Season == "Spring") %>%
  group_by(Year) %>%
  summarise(
    mean_lat = mean(LAT, na.rm = TRUE),
    min_lat = min(LAT, na.rm = TRUE),
    max_lat = max(LAT, na.rm = TRUE),
    mean_cpu = mean(wtcpue, na.rm = TRUE),
    min_cpu = min(wtcpue, na.rm = TRUE),
    max_cpu = max(wtcpue, na.rm = TRUE),
    max_dep = max(Depth, na.rm = TRUE),
    mean_dep = mean(Depth, na.rm = TRUE)
  ) %>%
  ungroup()

# Summer
at_sum <- at_data %>% 
  filter(Season == "Summer") %>%
  group_by(Year) %>%
  summarise(
    mean_lat = mean(LAT, na.rm = TRUE),
    min_lat = min(LAT, na.rm = TRUE),
    max_lat = max(LAT, na.rm = TRUE),
    mean_cpu = mean(wtcpue, na.rm = TRUE),
    min_cpu = min(wtcpue, na.rm = TRUE),
    max_cpu = max(wtcpue, na.rm = TRUE),
    mean_dep = mean(Depth, na.rm = TRUE),
    max_dep = max(Depth, na.rm = TRUE)
  ) %>%
  ungroup()

# Fall
at_fall <- at_data %>% 
  filter(Season == "Fall") %>% 
   group_by(Year) %>%
  summarise(
    mean_lat = mean(LAT, na.rm = TRUE),
    min_lat = min(LAT, na.rm = TRUE),
    max_lat = max(LAT, na.rm = TRUE),
    mean_cpu = mean(wtcpue, na.rm = TRUE),
    min_cpu = min(wtcpue, na.rm = TRUE),
    max_cpu = max(wtcpue, na.rm = TRUE),
    mean_dep = mean(Depth, na.rm = TRUE),
    max_dep = max(Depth, na.rm = TRUE)
  ) %>%
  ungroup()
```

```{r adepth, message=FALSE, warning=FALSE}
model1 <- lm(data = at_data, Depth ~ Year)
summary(model1)

# Seasonal plot
ggplot(at_sea, aes(x = Year, y=mean_dep, color = Season)) +
  geom_line() +
  geom_point() +
  labs(
    title = "Change in Depth",
    x = "Year",
    y = "Depth"
  ) +
  scale_y_reverse()+
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

```
## 2. Change in Lantitude
```{r alantitude, message=FALSE, warning=FALSE}
# Spring plot
ggplot(at_spr, aes(x = Year)) +
  geom_ribbon(aes(ymin = min_lat, ymax = max_lat), fill = "lightblue", alpha = 0.5) +
  geom_line(aes(y = mean_lat), color = "red") +
  geom_point(aes(y = mean_lat), color = "red") +
  labs(
    title = "Change in Latitude (Spring)",
    x = "Year",
    y = "Latitude"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

# Summer plot
ggplot(at_sum, aes(x = Year)) +
  geom_ribbon(aes(ymin = min_lat, ymax = max_lat), fill = "lightblue", alpha = 0.5) +
  geom_line(aes(y = mean_lat), color = "red") +
  geom_point(aes(y = mean_lat), color = "red") +
  labs(
    title = "Change in Latitude (Summer)",
    x = "Year",
    y = "Latitude"
  ) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

# Fall plot
ggplot(at_fall, aes(x = Year)) +
  geom_ribbon(aes(ymin = min_lat, ymax = max_lat), fill = "lightblue", alpha = 0.5) +
  geom_line(aes(y = mean_lat), color = "red") +
  geom_point(aes(y = mean_lat), color = "red") +
  labs(
    title = "Change in Latitude (Fall)",
    x = "Year",
    y = "Latitude"
  ) +
  xlim(1989, 2020) +
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

```
## 3. wtcpue ~ depth
```{r, message=FALSE, warning=FALSE}
model2 <- lm(data = at_data, wtcpue ~ Depth)
summary(model2)

ggplot(data = at_data, aes(y=Depth, x=wtcpue, color = Season))+
  geom_point(alpha=0.7,size=0.7)+
  scale_y_reverse()+
  labs(title = "Vertical Distribution of Atlantic Brief Squid",
       y = "Depth(m)",
       x = "Weight Count per Unit Effort")+
  theme_minimal()+
  xlim(0,2)

```

## 4. wtcpue ~ year
```{r, message=FALSE, warning=FALSE}
model3 <- lm(data = at_data, wtcpue ~ Year)
summary(model3)

ggplot(data = at_data, aes(y=wtcpue, x=Year, color = Season))+
  geom_point(alpha=0.7,size=0.7)+
  labs(title = "Atlantic Brief Squid",
       y = "Weight Count per Unit Effort",
       x = "Year")+
  theme_minimal()
```
## 5. wtcpue ~ season

ONE-WAY ANOVA test

Null Hypothesis: There are no differences in the means of wtcpue among seasons.
Alternative Hypothesis: There are differences in the means of wtcpue among seasons.

```{r, message=FALSE, warning=FALSE}
anova_result <- aov(wtcpue ~ Season, data = at_data)
summary(anova_result)
```


